version: 2

sources:
  - name: erp
    description: Fonte do SAP/ERP de vendas
    schema: erp_northwind
    tables:
      - name: products
      - name: categories
      - name: suppliers
      